### ISSUE TITLE
Can't start the UI

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-personal-backend-ui#9]
```
AttributeError: module 'ovos_backend_manager.__main__' has no attribute 'main'
Traceback (most recent call last):
  File "/home/ovos/.venv/bin/ovos-backend-manager", line 33, in <module>
    sys.exit(load_entry_point('ovos-backend-manager==0.0.1a1', 'console_scripts', 'ovos-backend-manager')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/bin/ovos-backend-manager", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 204, in load
    return functools.reduce(getattr, attrs, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ovos_backend_manager.__main__' has no attribute 'main'
```

**Comment by JarbasAl** [comment]
fixed
